name: Analyze Links and Style

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

  check-arm-templates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Test ARM Template for Internal Channel
      id: armtest-internal
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: ./azuredeploy-internal.json
    - name: Test ARM Template for Beta and Production Channel
      id: armtest-beta
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: .
        files: azuredeploy-beta.json,azuredeploy-prod.json
    - name: Test Nested ARM Templates
      id: armtest-nested
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: ./nestedtemplates
        files: appSvcDouble.json,appConfig-scepman.json,appConfig-certmaster.json,stgAccount.json,vault.json


    - name: Test ARM Result
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.armtest-internal.outputs.results)) }}"
        echo "${{ toJSON(fromJSON(steps.armtest-nested.outputs.results)) }}"