name: Analyze Links and Style

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

  analyze-powershell-script:
    runs-on: ubuntu-latest
    steps:
    - name: Run PSScriptAnalyzer
      uses: microsoft/psscriptanalyzer-action@main
      with:
        path: .\
        recurse: true 
        output: results.sarif

    - name: Upload PowerShell SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: PSScriptAnalyzer

  check-arm-templates:
    runs-on: ubuntu-latest
    steps:
    - name: Test ARM Templates
      id: armtest
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: .

    - name: Test ARM Result
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.armtest.outputs.results)) }}"    